'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SyncServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SyncServiceReference.ICacheSyncContract")>  _
    Public Interface ICacheSyncContract
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICacheSyncContract/ApplyChanges", ReplyAction:="http://tempuri.org/ICacheSyncContract/ApplyChangesResponse")>  _
        Function ApplyChanges(ByVal groupMetadata As Microsoft.Synchronization.Data.SyncGroupMetadata, ByVal dataSet As System.Data.DataSet, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncContext
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICacheSyncContract/GetChanges", ReplyAction:="http://tempuri.org/ICacheSyncContract/GetChangesResponse")>  _
        Function GetChanges(ByVal groupMetadata As Microsoft.Synchronization.Data.SyncGroupMetadata, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncContext
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICacheSyncContract/GetSchema", ReplyAction:="http://tempuri.org/ICacheSyncContract/GetSchemaResponse")>  _
        Function GetSchema(ByVal tableNames() As String, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncSchema
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICacheSyncContract/GetServerInfo", ReplyAction:="http://tempuri.org/ICacheSyncContract/GetServerInfoResponse")>  _
        Function GetServerInfo(ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncServerInfo
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ICacheSyncContractChannel
        Inherits SyncServiceReference.ICacheSyncContract, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class CacheSyncContractClient
        Inherits System.ServiceModel.ClientBase(Of SyncServiceReference.ICacheSyncContract)
        Implements SyncServiceReference.ICacheSyncContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ApplyChanges(ByVal groupMetadata As Microsoft.Synchronization.Data.SyncGroupMetadata, ByVal dataSet As System.Data.DataSet, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncContext Implements SyncServiceReference.ICacheSyncContract.ApplyChanges
            Return MyBase.Channel.ApplyChanges(groupMetadata, dataSet, syncSession)
        End Function
        
        Public Function GetChanges(ByVal groupMetadata As Microsoft.Synchronization.Data.SyncGroupMetadata, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncContext Implements SyncServiceReference.ICacheSyncContract.GetChanges
            Return MyBase.Channel.GetChanges(groupMetadata, syncSession)
        End Function
        
        Public Function GetSchema(ByVal tableNames() As String, ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncSchema Implements SyncServiceReference.ICacheSyncContract.GetSchema
            Return MyBase.Channel.GetSchema(tableNames, syncSession)
        End Function
        
        Public Function GetServerInfo(ByVal syncSession As Microsoft.Synchronization.Data.SyncSession) As Microsoft.Synchronization.Data.SyncServerInfo Implements SyncServiceReference.ICacheSyncContract.GetServerInfo
            Return MyBase.Channel.GetServerInfo(syncSession)
        End Function
    End Class
End Namespace
