'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class CacheClientSyncProvider
    Inherits Microsoft.Synchronization.Data.SqlServerCe.SqlCeClientSyncProvider
    
    Public Sub New()
        MyBase.New
        Me.ConnectionString = Global.SyncServices_NTierDownload_VB.My.MySettings.Default.ClientNorthwindConnectionString
    End Sub
    
    Public Sub New(ByVal connectionString As String)
        MyBase.New
        Me.ConnectionString = connectionString
    End Sub
End Class

Partial Public Class CacheSyncAgent
    Inherits Microsoft.Synchronization.SyncAgent
    
    Private _customersSyncTable As CustomersSyncTable
    
    Partial Private Sub OnInitialized()
    End Sub
    
    Public Sub New()
        MyBase.New
        Me.InitializeSyncProviders
        Me.InitializeSyncTables
        Me.OnInitialized
    End Sub
    
    Public Sub New(ByVal remoteSyncProviderProxy As Object)
        MyBase.New
        Me.InitializeSyncProviders
        Me.InitializeSyncTables
        Me.RemoteProvider = New Microsoft.Synchronization.Data.ServerSyncProviderProxy(remoteSyncProviderProxy)
        Me.OnInitialized
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property Customers() As CustomersSyncTable
        Get
            Return Me._customersSyncTable
        End Get
        Set
            Me.Configuration.SyncTables.Remove(Me._customersSyncTable)
            Me._customersSyncTable = value
            Me.Configuration.SyncTables.Add(Me._customersSyncTable)
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitializeSyncProviders()
        'Create SyncProviders.
        Me.LocalProvider = New CacheClientSyncProvider
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitializeSyncTables()
        'Create SyncTables.
        Me._customersSyncTable = New CustomersSyncTable
        Me._customersSyncTable.SyncGroup = New Microsoft.Synchronization.Data.SyncGroup("CustomersSyncTableSyncGroup")
        Me.Configuration.SyncTables.Add(Me._customersSyncTable)
    End Sub
    
    Partial Public Class CustomersSyncTable
        Inherits Microsoft.Synchronization.Data.SyncTable
        
        Partial Private Sub OnInitialized()
        End Sub
        
        Public Sub New()
            MyBase.New
            Me.InitializeTableOptions
            Me.OnInitialized
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitializeTableOptions()
            Me.TableName = "Customers"
            Me.CreationOption = Microsoft.Synchronization.Data.TableCreationOption.DropExistingOrCreateNewTable
        End Sub
    End Class
End Class
